version: 2

source:
  enabled: true
  name_template: "{{ .ProjectName }}-{{ .Version }}"

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - binary: "{{ tolower .ProjectName }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X github.com/hibare/GoS3Backup/internal/version.CurrentVersion={{.Version}}

universal_binaries:
  - replace: true
    name_template: "{{ tolower .ProjectName }}"

nfpms:
  - id: nfpms
    package_name: "gos3backup"
    file_name_template: >-
      {{- trimsuffix .ConventionalFileName .ConventionalExtension -}}
      {{- if and (eq .Arm "6") (eq .ConventionalExtension ".deb") }}6{{ end -}}
      {{- if not (eq .Amd64 "v1")}}{{ .Amd64 }}{{ end -}}
      {{- .ConventionalExtension -}}
    vendor: Hibare.
    homepage: https://github.com/hibare/GoS3Backup
    maintainer: Hibare <admin@hibare.in>.
    description: |-
      Software to perform daily backups to S3.
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: scripts/gos3backup.service
        dst: /etc/systemd/system/gos3backup.service
    scripts:
      postinstall: "scripts/postinstall.sh"
      preremove: "scripts/preremove.sh"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

publishers:
  - name: fury.io
    ids:
      - nfpms
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/hibare/
